[EDScreenshot]
screenshot = no_modifiers VK_F12
;To activate ED Screenshot for HD captures, remove the ';' before the next line
;screenshothd = ALT VK_F10
format = tiff
;You can instead output OpenEXR format with
;format = exr
